### PR TITLE
New options and clarified docs and examples

### PR DESCRIPTION
**Pull request by GuyPaddock**
I've added new options for determining scope by parameter values rather than just by parameter names. (And provided test cases for the new options, too.)

I've also clarified a few spots in the docs that were unclear.

### CODE REVIEW

**Comment by GuyPaddock** [comment]
Any chance this will get merged in or commented on soon?

**Comment by GuyPaddock** [comment]
Is this project actively maintained?

**Comment by carlosantoniodasilva** [comment]
Yes, it is, but you know, life happens sometimes :).

Thank you so much for your pull request, but I think most of these options could be handled by scopes themselves rather than extending the library with more options. For example, if/unless value could be conditionals on the scope itself - whenever it makes sense, and no value passing sounds like it could be handled by boolean option + allow blank to me (just by glancing at it). Unfortunately I can't build any example off the top of my head right now, but my initial opinion is that I'd rather not add a good amount of code to the library at this point for handling every edge case with options.

Thanks again for your contribution.

**Comment by GuyPaddock** [comment]
You appear to have completely missed the point of this PR, despite the fact that I provided updated documentation, examples, and unit tests to illustrate how the new options work.

Were it possible to have implemented the desired functionality using the options already provided, I would not have bothered to implement the new options as it would be easier not to maintain a separate fork. As it stands, it is not possible to get the results required using what has_scope already provides.

Consider a JSON "Orders" endpoint that must take the following query string param:

- `filter[status]`: can be either `new`, `pending`, or `completed`

So that a sample URL would look like:
http://mysite.com/api/orders?filter[status]=new

This allows a client to choose whether it wants new orders, pending orders, or completed orders (you can think of it as if the user was picking the status from a drop-down on a search page). The statuses are mutually exclusive (a new order cannot be pending or completed, etc).

New, pending, and completed all map to specific scopes on the `Order` model object.

How would you use the existing support in has_scope to implement this interface? Per the docs and your own comment, the only way to implement scoping like this would be to declare separate boolean QS values, like this:

- `filter[new]`: can be either `true` or `false`
- `filter[pending]`: can be either `true` or `false`
- `filter[completed]`: can be either `true` or `false`

But that is confusing, wasteful, and does not comply with the original required interface. Now the URL looks like this:
http://mysite.com/api/orders?filter[new]=true&filter[pending]=false&filter[completed]=false

And leads to confusing results if more than one is `true`. One could guard against this by making every invocation of has_scope for one scope exclude the others using `:unless`, but then we're violating the Ruby convention of Don't Repeat Yourself.

Similarly, it does not make sense for the scope to have to handle the check on these values, since this is purely a concern related to the query string handling. The scope is merely there to provide a query, not determine how to handle a value passed-in from the QS.

Finally, I don't see how you can say that you would not like to add "a good amount of code to the library at this point", since:

1. I have ensured that the new functionality does not break existing functionality by applying the existing unit tests.
2. I have ensured that the new functionality has new, corresponding unit tests.
3. I have demonstrated that the functionality requested is not an edge case.

Initially, I requested some help with this module because some things did not make sense, and your response at the time was to sort things out, make things clearer, and then issue a PR. Now, you are saying that even if I issue a PR after making things cleaner and easier to use, you will not consider merging it.

Please give this PR more careful consideration.

**Comment by josevalim** [comment]
> You appear to have completely missed the point of this PR, despite the fact that I provided updated documentation, examples, and unit tests to illustrate how the new options work.

I am pretty sure there are a thousand ways to phrase this in a more polite way. One of them being completely removing the sentence.

In any case, I agree with @carlosantoniodasilva that it could be achievable with what we have today:

     scope :by_status, -> status { where(status: status) }

What you are adding to `has_scope` is exactly options for validating the status given the case above. You are right that the scope should not be the one validating but it does NOT need to be done by the scope, any other function, filter and so on could do it.

Honestly, I would rather read some code that explicitly performs such status validation than trying to parse the has_scope DSL with four new options. For example:

    has_scope :dogwood, :as => :tree_type, :if_value => :dogwood, :no_value_passing => true

Will your co-workers, or even you in 3-months, be able to look at the code above and say: "I know exactly what this is doing"? I am certain **I won't**.

This PR is technically good: it has code, tests and documentation. However, any code, regardless of how well written, is code complexity and adding 4 new options to `has_scope` will definitely make code using `has_scope` harder to read and write.

So I am :-1: on this functionality too in favor of simplicity. The `:in` and `:using` options were already pushing it to the limit and I wouldn't like to take it further. Thanks!

**Comment by GuyPaddock** [comment]
@josevalim: I agree that my response was impolite, but it's also frustrating when a maintainer finally responds and dismisses a feature that took several hours to carefully craft without providing the level of detail that you have just provided.

Regarding your example, this still would not provide the desired feature. That appears to just define a new scope that takes an argument. Is not the point of `has_scope` to map existing scopes on a ActiveModel object to the QS? In my example, there are three status **scopes**; it's not the case that we're simply accepting the query string blindly and passing it into a scope.

The main reason for this is security -- we're choosing to use `has_scope` because we can explicitly choose which scopes we expose, by name.

I agree that in the example you've called out, the DSL is a bit verbose, which is why the :scope_by_value option exists. Simplicity is a noble goal, but this is a perfect situation in which more expressiveness is called for. In order for `has_scope` to work for this scenario, we're technically using `:in`, `:using`, and `:scope_by_value` since the value we want is under `filter[scope]`.

**Comment by josevalim** [comment]
>  Is not the point of has_scope to map existing scopes on a ActiveModel object to the QS?

Not necessarily. You will often need to change your scopes to conform to what has_scope is going to give you and this is one of those cases. Or handle it in a filter. The issue here is exactly that: we are adding options and options to `has_scope` to massage the data. Today we have an option to traverse hashes, then we are adding another to validate the value in an array and so on. This is going to lead to an extremely wide and confusing API.

> Simplicity is a noble goal, but this is a perfect situation in which more expressiveness is called for. 

We will have to agree to disagree here. I would take a code that is easier to read over the easy to write any time, any day.

**Comment by GuyPaddock** [comment]
> You will often need to change your scopes to conform to what has_scope is going to give you and this is one of those cases. Or handle it in a filter.

But, this leads to more confusing code for our team since we now have different names for the scopes than we declare using `has_scope`. All of the docs for has_scope indicate that the name of the scope in the model matches what is passed to `has_scope`.

The gem description is:
> Has scope allows you to easily create controller filters based on your resources named scopes.

Which indicates that the resources scopes should remain as they are.

I get the desire to keep the code simple and straightforward, and acknowledge that there may be a clearer way to have named the symbols for indicating that the scope is selected by the value of a param, but I still don't see how it's that much to ask for `has_scope` to offer the option of applying one of several approved scopes based on what's been passed for a single QS param.

The case of having multiple boolean QS params is significantly more awkward to write, understand, and read. In addition, how is it easier to read and understand having to write a filter mix-in in every model object, *and then* adding a `has_scope` statement that does not take any of the scopes defined on the model?

I understand that the goal is to make code easier to read, but the approach you proposed is still not easier to read.

**Comment by carlosantoniodasilva** [comment]
Hey @GuyPaddock, I'm sorry if my previous comment seemed rude, I didn't mean to be, I just tried to reply to your feedback about the project being actively maintained. No, I did not review the code carefully, just glanced at it. And yes, I do understand what it's trying to achieve, I've done similar things in the past too.

What I am trying to clarify is that I think it seems much more simpler having a `filter` scope (or class method) that handles scenarios like that:

```ruby
scope :filter, -> status {
  send(status) if %w(new pending completed).include?(status)
  # or you could use a by_status scope like José mentioned.
}
```

It seems much easier to follow what's going on, what are the available filters/status, how to extend them, without any other DSL magic. I could come back to this code a year from now and understand what it means. Making that a constant or an enum would allow to automatically add new filters/statuses, again without having to deal with has_scope.

I wanted to build a better example, hopefully this will be enough. Thanks.

**Pull request closed without merging**
